#!/usr/bin/env bash
# Wide system configuration script

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
}" > /etc/nginx/sites-available/default
echo "https://github.com/sintayehuCSE" > /var/www/html/redirect_me
new_config_line="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/sintayehuCSE permanent;"
sudo sed -i "s/server_name _;/${new_config_line}/" /etc/nginx/sites-enabled/default
new_cnfg_line="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/v\r\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/${new_cnfg_line}/" /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
service nginx restart
