#!/usr/bin/env bash
# A BASH script that pings an IP address passed as an argument
# Requirements:
#    1. Accepts a string as an argument
#    2. Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#    3. Ping the IP 5 times
if [ "$#" -ne 1 ];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
