#!/usr/bin/env bash
# A script that debug for a configuration fault that is preventing nginx from listening at port 20

new="listen 80 default_server;"
old="listen 8080 default_server;"
sed -i "s/$old/$new/" /etc/nginx/sites-available/default

service nginx restart
