#!/usr/bin/env bash
# A script that debug for a configuration fault that is preventing nginx from listening at port 20

new_port="80 default_server"
old_port="8080 default_server"
sed -i "s/{$old_port}/{$new_port}/" /etc/nginx/sites-enabled/default

service nginx restart
