#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd
# It will only display `username`, `user ID`, and `Home directory path for the user`
while read -r passwd
do
    echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
