#!/usr/bin/env bash
#A Bash script that display the time for 12 hours and 59 minutes

hour=0
min=1

while [ $hour -lt 12 ]
do
    echo "Hour: $hour"
    while [ $min -le 59 ]
    do
	echo "$min"
	(( min++ ))
    done
    (( min-=58 ))
    (( hour++ ))
done
